is_a_sister(naliaka,njeri).
is_a_sister(njeri,naliaka).
is_a_mother(naliaka,mbugua).
is_a_mother(mwende,naliaka).
is_a_mother(njeri,kipyegon).
is_a_mother(achieng,wasike).
is_a_father(onyango,njeri).
is_a_father(onyango,naliaka).
is_a_father(wambua,wasike).
is_a_father(wasike,kipyegon).
is_a_father(ali,mbugua).
is_a_husband(onyango,mwende).
is_a_husband(wambua,achieng).
is_a_husband(wasike,njeri).
is_a_husband(ali,naliaka).
is_a_wife(mwende,onyango).
is_a_wife(achieng,wambua).
is_a_wife(njeri,wasike).
is_a_wife(naliaka,ali).
is_a_grandfather(X,Y):-is_a_father(X,M),(is_a_father(M,Y);is_a_mother(M,Y)).
is_a_grandmother(X,Y):-is_a_mother(X,M),(is_a_mother(M,Y);is_a_father(M,Y)).
is_a_aunt(X,Y):-is_a_sister(X,M),is_a_mother(M,Y).
is_a_paternal_grandfather(X,Y):-is_a_father(X,M),is_a_father(M,Y).
is_a_maternal_grandmother(X,Y):-is_a_mother(X,M),is_a_mother(M,Y).
is_a_maternal_grandfather(X,Y):-is_a_father(X,M),is_a_mother(M,Y).
is_a_paternal_grandmother(X,Y):-is_a_mother(X,M),is_a_father(M,Y).
is_a_paternal_aunt(X,Y):-is_a_sister(X,M),is_a_father(M,Y).
is_a_maternal_aunt(X,Y):-is_a_sister(X,M),is_a_mother(M,Y).
/*CCS/00022/020*/