male(onyango).
male(wambua).
male(ali).
male(wasike).
male(kipyegon).
female(mwende).
female(achieng).
female(naliaka).
female(njeri).
parent(onyango,naliaka).
parent(naliaka,njeri).
parent(wambua,wasike).
parent(achieng,wasike).
parent(naliaka,mbugua).
parent(ali,mbugua).
parent(njeri,kipyegon).
parent(wasike,kipyegon).
parent(onyango,njeri).
parent(mwende,njeri).
parent(mwende,naliaka).
father(X,Y):-male(X),parent(X,Y).
mother(X,Y):-female(X),parent(X,Y).
brother(X,Y):-male(X),parent(M,X),parent(M,Y).
sister(X,Y):-female(X),parent(M,X),parent(M,Y).
uncle(X,Y):-male(X),brother(X,Z),parent(Z,Y).